# Site settings
title: Design Portfolio (Test)
email: juanca.talavera@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Una prueba de como funciona Jekyll, siguiendo un tutorial bastante interesante. Veremos!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: juancatalavera
github_username:  juancatalavera
google_username: juan.catalavera

permalink: /:categories/:title

links:
  -title: about
   url:/about
  -title: work
   url:/work
  -title: articles
   url:/articles
  -title: hire me
   url:/hire-me

# Build settings
markdown: kramdown
